services:
  web-dev:
    image: node:25-alpine
    container_name: lp-financial-board
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: sh -c "npm i && npm start"
    user: node
